In [60]:
# libraries 
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
import seaborn as sns

# data
df = pd.read_csv('usa_owid-covid-data.csv')

In [61]:
df.shape[0]
df.head()

,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,icu_patients,...,positive_rate,tests_per_case,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,new_people_vaccinated_smoothed,stringency_index,cci
0,North America,United States,2020-02-01,8,0,0.857,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,101.2
1,North America,United States,2020-03-01,32,7,2.286,1.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,100.2
2,North America,United States,2020-04-01,227893,35814,22721.714,6996.0,1637.0,804.286,NaN,...,0.199,5.0,NaN,NaN,NaN,NaN,NaN,NaN,72.69,99.0
3,North America,United States,2020-05-01,1115845,34846,28132.143,68515.0,1880.0,1902.714,NaN,...,0.136,7.4,NaN,NaN,NaN,NaN,NaN,NaN,72.69,98.5
4,North America,United States,2020-06-01,1808724,17853,20389.857,108613.0,767.0,945.429,NaN,...,0.064,15.6,NaN,NaN,NaN,NaN,NaN,NaN,72.69,98.5

In [62]:
# df = df.replace([np.nan, -np.inf], np.nan, inplace = True).astype(dtype('float64'))
df = df.dropna()

In [63]:
x_columns = ['total_cases', 'new_cases', 'total_deaths', 'new_deaths', 'positive_rate', 'stringency_index']
x = df[x_columns]
y = df['cci']
linear_model = LinearRegression()
linear_model.fit(x,y)

LinearRegression()

In [64]:
sns.lmplot(x = x, y = y, data = df)

/Users/mauricefreese/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/arraysetops.py:270: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.asanyarray(ar)

ValueError: could not broadcast input array from shape (18,6) into shape (18,)